version: "3.3"
services:
  app:
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - es
      - db
    volumes:
      - .:/app
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: bash -c "python manage.py migrate && python manage.py upload_dummy_data && python manage.py runserver 0.0.0.0:8000"


  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  es:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.1"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
          - esdata:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node


volumes:
  esdata:
    driver: local
